server:
  port: 8080

spring:
  application:
    name: pixel-gateway
  cloud:
    nacos:
      discovery: # nacos客户端注册发现
        server-addr: localhost:8848
    gateway:
      routes: # 网关路由配置
        # user
        - id: pixel-user # 路由id，自定义，只要唯一即可
          uri: lb://pixel-user # 路由的目标地址
          predicates: #路由断言，判断请求是否符合路由规则的条件
            - Path=/api/pUser/**,/api/pFollow/** # 这个是按照路径匹配，只要以/api/pUser/开头就符合要求
        # pixel-auth-server
        - id: pixel-auth-server
          uri: lb://pixel-auth-server
          predicates:
            - Path=/api/auth/**
        # pixel-post
        - id: pixel-post
          uri: lb://pixel-post
          predicates:
            - Path=/api/pPost/**,/api/pPostContent/**,/api/pTag/**,/api/pPostStar/**,/api/pPostCollection/**
        # pixel-comment
        - id: pixel-comment
          uri: lb://pixel-comment
          predicates:
            - Path=/api/pComment/**,/api/pCommentContent/**,/api/pCommentReply/**