server:
  port: 8902

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pixel_ccp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: wht123456
    driver‐class‐name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery: # nacos客户端注册发现
        server-addr: localhost:8848
  rabbitmq:
    host: localhost # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: xxx # 用户名
    password: xxx # 密码
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s